# Generated by Django 3.2.10 on 2022-02-03 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='guest_user',
            field=models.JSONField(),
        ),
    ]
