# Generated by Django 3.2.10 on 2022-02-03 13:17

import datetime
from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payment', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Courier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('request_and_response_sample', models.JSONField(default={'authorize': {'data': {}, 'header': {}, 'http_method': 'get or post', 'url': ''}, 'authorize_response': {'jwt_token': {'id_token': 'token'}}, 'create_order': {'body': {}, 'header': {}, 'http_method': 'get or post', 'url': ''}, 'get_price': {'body': {}, 'header': {}, 'http_method': 'get or post', 'url': ''}, 'order_status': {'body': {}, 'header': {}, 'http_method': 'get or post', 'url': ''}})),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ShippingOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest_user', django.contrib.postgres.fields.jsonb.JSONField()),
                ('guest_user_address', django.contrib.postgres.fields.jsonb.JSONField()),
                ('start', models.DateTimeField(default=datetime.datetime(2022, 2, 3, 13, 17, 50, 644347, tzinfo=utc))),
                ('shipping_price', models.DecimalField(decimal_places=2, max_digits=9)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('courier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipping_order', to='shipping.courier')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipping_info', to='payment.order')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='all_shipping_info', to=settings.AUTH_USER_MODEL)),
                ('user_address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='all_shipping_info', to='accounts.useraddress')),
            ],
        ),
    ]
