# Generated by Django 3.2.10 on 2022-02-04 13:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import shipping.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Courier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('request_and_response_sample', models.JSONField(default=shipping.models.request_and_response_sample)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ShippingOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest_user', models.JSONField()),
                ('guest_user_address', models.JSONField()),
                ('status', models.CharField(choices=[('new', 'new'), ('cancelled', 'cancelled'), ('done', 'done')], max_length=11)),
                ('start', models.DateTimeField(default=django.utils.timezone.now)),
                ('shipping_price', models.DecimalField(decimal_places=2, max_digits=9)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('courier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipping_order', to='shipping.courier')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipping_info', to='payment.order')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='all_shipping_info', to=settings.AUTH_USER_MODEL)),
                ('user_address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='all_shipping_info', to='accounts.useraddress')),
            ],
        ),
    ]
