# Generated by Django 3.2.10 on 2022-02-03 13:25

from django.db import migrations, models
import django.utils.timezone
import shipping.models


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courier',
            name='request_and_response_sample',
            field=models.JSONField(default=shipping.models.request_and_response_sample),
        ),
        migrations.AlterField(
            model_name='shippingorder',
            name='guest_user',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='shippingorder',
            name='guest_user_address',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='shippingorder',
            name='start',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
